// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CrispArchitecture.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    public class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrispArchitecture.Domain.Entities.Test", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("TestEmail")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TestValue1")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TestValue2")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Tests");
            });
#pragma warning restore 612, 618
        }
    }
}